class CfgWLRequisitionPresets
{
	class A3ReduxAll
	{
		class WEST
		{
			class Infantry
			{
				class UK3CB_CW_US_B_LATE_RIF_1 				{cost = 20;		requirements[]={};	};	// "Rifleman"
				class UK3CB_CW_US_B_LATE_CREW 				{cost = 15;		requirements[]={};	};	// "Crewman"
				class UK3CB_CW_US_B_LATE_HELI_PILOT 		{cost = 10;		requirements[]={};	};	// "Helicopter Pilot"
				class UK3CB_CW_US_B_LATE_JET_PILOT 			{cost = 10;		requirements[]={};	};	// "Pilot"
				class UK3CB_CW_US_B_LATE_GL 				{cost = 50;		requirements[]={};	};	// "Grenadier"				
				class UK3CB_CW_US_B_LATE_MD					{cost = 20;		requirements[]={};	};	// "Combat Life Saver"
				class UK3CB_CW_US_B_LATE_AR					{cost = 50;		requirements[]={};	};	// "Autorifleman"
				class UK3CB_CW_US_B_LATE_MG_ASST			{cost = 25;		requirements[]={};	};	// "Ammo Bearer"
				class UK3CB_CW_US_B_LATE_MK					{cost = 60;		requirements[]={};	};	// "Marksman"
				class UK3CB_CW_US_B_LATE_ENG				{cost = 100;	requirements[]={};	};	// "Repair Specialist"
				class UK3CB_CW_US_B_LATE_MG					{cost = 80;		requirements[]={};	};	// "Heavy Gunner"
				class UK3CB_CW_US_B_LATE_LAT				{cost = 100;	requirements[]={};	};	// "Rifleman (AT)"
				class UK3CB_CW_US_B_LATE_AT				{cost = 100;	requirements[]={};	};	// "Rifleman (AT)"
				class UK3CB_CW_US_B_LATE_AT_ASST				{cost = 100;	requirements[]={};	};	// "Rifleman (AT)"
				class UK3CB_CW_US_B_LATE_AA_ASST				{cost = 100;	requirements[]={};	};	// "Rifleman (AT)"
				class UK3CB_CW_US_B_LATE_AA					{cost = 150;	requirements[]={};	};	// "Missile Specialist (AA)"
				class UK3CB_CW_US_B_LATE_SF_SNI				{cost = 100;	requirements[]={};	};	// "Sniper"
				//class B_Captain_Dwarden_F					{cost = 150;	requirements[]={};	};	// "Dwarden"
			};
			class Vehicles
			{
				class UK3CB_LNM_B_TT650						    {cost =  20;	requirements[]={};	};	// "Quad Bike"
				class UK3CB_CW_US_B_LATE_M151_Jeep_Closed		{cost = 100;	requirements[]={};	};	// "Prowler (Unarmed)"
				class UK3CB_CW_US_B_LATE_M1025_Unarmed			{cost = 200;	requirements[]={};	};	// "Hunter"
				class UK3CB_CW_US_B_LATE_M939				    {cost = 200;	requirements[]={};	};	// "HEMTT Transport"
				class UK3CB_CW_US_B_LATE_M939_Fuel				{cost = 500;	requirements[]={};	};	// "HEMTT Fuel"
				class UK3CB_CW_US_B_LATE_M113_AMB			    {cost = 350;	requirements[]={};	};	// "HEMTT Medical"
				class UK3CB_CW_US_B_LATE_M151_Jeep_HMG			{cost = 350;	requirements[]={};	};	// "Prowler (HMG)"
				class UK3CB_CW_US_B_LATE_M151_Jeep_TOW			{cost = 1000;	requirements[]={};	};	// "Prowler (AT)"
				class UK3CB_CW_US_B_LATE_M977A4_Repair			{cost = 2000;	requirements[]={};	};	// "HEMTT Repair"
				class UK3CB_CW_US_B_LATE_M939_Reammo			{cost = 3000;	requirements[]={};	};	// "HEMTT Ammo"
				
				class UK3CB_CW_US_B_LATE_M1025_M2				{cost = 1000;	requirements[]={};	};	// "Hunter HMG"
				class UK3CB_CW_US_B_LATE_M1025_MK19				{cost = 1200;	requirements[]={};	};	// "Hunter GMG"
				class UK3CB_CW_US_B_LATE_M113_M2				{cost = 1000;	requirements[]={};	};	// "M113 HMG"
				class UK3CB_CW_US_B_LATE_M113_MK19				{cost = 1000;	requirements[]={};	};	// "M113 GMG"												
				class UK3CB_CW_US_B_LATE_M2A2				    {cost = 3500;	requirements[]={};	};	// "BLUFOR Gorgon"
				class UK3CB_CW_US_B_LATE_LAV25				    {cost = 2200;	requirements[]={};	};	// "AMV-7 Marshall"
				class UK3CB_CW_US_B_LATE_AAV				    {cost = 1800;	requirements[]={};	};	// "IFV-6c Panther"
				class UK3CB_LDF_B_T810_ZU23					    {cost = 1500;	requirements[]={};	};	// "Zu-23"
				class UK3CB_LDF_B_ZsuTank					    {cost = 2500;	requirements[]={};	};	// "Shilka"
				class UK3CB_LDF_B_2S6M_Tunguska					{cost = 3000;	requirements[]={};	};	// "Tunguska"
				class UK3CB_KRG_B_M270_Avenger					{cost = 4000;	requirements[]={};	};	// "Avenger"
				class UK3CB_CW_US_B_EARLY_M60a1					{cost = 6000;	requirements[]={};	};	// "M2A1 Slammer"
				class UK3CB_CW_US_B_LATE_M60a3					{cost = 8000;	requirements[]={};	};	// "M2A1 Slammer UP"
				class UK3CB_CW_US_B_LATE_M1A1			        {cost = 11000;	requirements[]={};	};	// "Rhino MGS UP" 
				class UK3CB_CW_US_B_LATE_M109					{cost = 18000;	requirements[]={};	};	// "M4 Scorcher"
				class UK3CB_CW_US_B_LATE_M270_MLRS_HE			{cost = 20000;	requirements[]={};	};	// "MLRS" 				 
				 
				 
			};
			class Aircraft
			{
				class UK3CB_CW_US_B_LATE_UH1H				    {cost = 500;	requirements[]={"H"};	};	// "MH-9 Hummingbird"
				class UK3CB_CW_US_B_LATE_UH1H_GUNSHIP		    {cost = 3000;	requirements[]={"H"};	};	// "AH-9 Pawnee"
				class UK3CB_CW_US_B_LATE_UH60M2					{cost = 1000;	requirements[]={"H"};	};	// "UH-80 Ghost Hawk"
				class UK3CB_CW_US_B_LATE_CH47					{cost = 1000;	requirements[]={"H"};	};	// "CH-67 Huron"
				class UK3CB_CW_US_B_LATE_AH64		            {cost = 15000;	requirements[]={"H"};	};	// "AH-64 Blackfoot"
				class UK3CB_CW_US_B_LATE_AH1Z					{cost = 14000;	requirements[]={"A"};	};	// "AH1z"
                class UK3CB_CW_US_B_LATE_C130J                  {cost = 2000;	requirements[]={"A"};	};	// "C130"
				class UK3CB_CW_US_B_LATE_Cessna_T41_Armed_M134  {cost = 2000;	requirements[]={"A"};	};	// "Minigun Maescealearano (CAS)"
				class RHSGREF_A29B_HIDF		                    {cost = 15000;	requirements[]={"A"};	};	// "Super Tucano (CAS)"
				class UK3CB_CW_US_B_LATE_A10		            {cost = 18000;	requirements[]={"A"};	};	// "A-10 Wipeout (CAS)"
				class UK3CB_B_Mystere_HIDF_AA1					{cost = 20000;	requirements[]={"A"};	};	// "mysterie";
				class rhs_l159_cdf_b_CDF					    {cost = 35000;	requirements[]={"A"};	};	// "L159";
				//class B_Plane_Fighter_01_Stealth_F			{cost = 40000;	requirements[]={"A"};	};	// "F/A-181 Black Wasp II Stealth";
				
			};
			class Naval
			{
				class rhsgref_hidf_canoe			        {cost = 20;	requirements[]={"W"};	};	// "LOL"
				class UK3CB_CHD_B_Small_Boat_Wood			{cost = 50;	requirements[]={"W"};	};	// "Drveni"
				class UK3CB_CHD_B_Small_Boat_Closed			{cost = 100;	requirements[]={"W"};	};	// "Barka"
				class UK3CB_CHC_B_Fishing_Vessel			{cost = 100;	requirements[]={"W"};	};	// "Barka velika"				
				class UK3CB_MDF_B_RHIB_Gunboat				{cost = 100;	requirements[]={"W"};	};	// "Speedboat Minigun"
				class UK3CB_CHD_B_Fishing_Boat_VIV_FFV		{cost = 100;	requirements[]={"W"};	};	// "Gun slow"
				class UK3CB_CHD_B_Fishing_Boat_DSHKM		{cost = 100;	requirements[]={"W"};	};	// "Gun slow"
				class UK3CB_CHD_B_Fishing_Boat_SPG9			{cost = 100;	requirements[]={"W"};	};	// "Gun slow"
				class UK3CB_CHD_B_Fishing_Boat_Zu23			{cost = 100;	requirements[]={"W"};	};	// "Gun slow"
				class UK3CB_CHD_B_Fishing_Boat_Zu23_front	{cost = 100;	requirements[]={"W"};	};	// "Gun slow"
				class rhsusf_mkvsoc							{cost = 1500;	requirements[]={"W"};	};	// "BIG"
			};
			class Gear
			{
				class UK3CB_M16A1_Equipbox_Blufor			{cost = 100;	requirements[]={};	};	// "Basic Weapons [NATO]"
				class UK3CB_MP5_Equipbox_Blufor				{cost = 100;	requirements[]={};	};	// "Basic Weapons [NATO]"
				class UK3CB_STGW57_5104_Equipbox_Blufor		{cost = 100;	requirements[]={};	};	// "Basic Weapons [NATO]"
				class UK3CB_M60_Equipbox_Blufor				{cost = 100;	requirements[]={};	};	// "Basic Weapons [NATO]"
				class UK3CB_MG3_Equipbox_Blufor				{cost = 100;	requirements[]={};	};	// "Basic Weapons [NATO]"
				class UK3CB_AUGA1_Equipbox_Blufor			{cost = 100;	requirements[]={};	};	// "Basic Weapons [NATO]"
				class Item_rhs_weap_fim92					{cost = 500;	requirements[]={};	};	// "Launchers [NATO]"
				class Box_NATO_AmmoVeh_F					{cost = 800;	requirements[]={};	};	// "Vehicle Ammo [NATO]"
			};
			class Defences
			{
				class UK3CB_CW_US_B_LATE_M240_Low			{cost = 300;	requirements[]={};	};	// "Mk30 HMG .50"
				class UK3CB_CW_US_B_LATE_M240_High			{cost = 400;	requirements[]={};	};	// "Mk30 HMG .50 (Raised)"
				class UK3CB_CW_US_B_LATE_MK19_TriPod		{cost = 550;	requirements[]={};	};	// "Mk32 GMG 20 mm"
				class UK3CB_CW_US_B_LATE_Stinger_AA_pod		{cost = 300;	requirements[]={};	};	// "Static Titan Launcher (AA) [NATO]"
				class UK3CB_CW_US_B_LATE_TOW_TriPod			{cost = 300;	requirements[]={};	};	// "Static Titan Launcher (AT) [NATO]"
				class UK3CB_CW_US_B_LATE_Searchlight		{cost = 50;	requirements[]={};	offset[]={0, 5.3, 0};};	// "MIM-145 Defender"
				class B_Radar_System_01_F					{cost = 1000;	requirements[]={};	offset[]={0, 5.3, 0};};	// "AN/MPQ-105 Radar"
				class UK3CB_CW_US_B_LATE_M252				{cost = 6500;	requirements[]={};	};	// "Mortar"
				class UK3CB_CW_US_B_LATE_M119				{cost = 7000;	requirements[]={};	};	// "Mortar"				
				class UK3CB_CW_US_B_LATE_M240_nest			{cost = 800;	requirements[]={};	};	// "m240 nest" 
				class Land_BagFence_Round_F					{cost = 250;	requirements[]={};	offset[]={0, 2, 0};};	// "Semi Circle Sand bags"
				class Land_Razorwire_F						{cost = 250;	requirements[]={};	offset[]={0, 5, 0};};	// "Razor Wire Fence"
				class Land_DragonsTeeth_01_1x1_new_F		{cost = 500;	requirements[]={};	offset[]={0, 2, 0};};	// "Tank barrier"

				      	

				//class B_UAV_05_F 							{cost = 25000;	requirements[]={"A"};	};	// "UCAV";
				//class B_UAV_02_F 							{cost = 25000;	requirements[]={"A"};	};	// "greyhawk AT";
				//class B_UAV_02_CAS_F						{cost = 25000;	requirements[]={"A"};	};	// "greyhawk LGB";
				//class B_T_UAV_03_F 						{cost = 25000;	requirements[]={"A"};	};	// "Firescout";
				//class B_UAV_01_F 							{cost = 500;	requirements[]={};	};	// "AR-2 Darter";
				//class B_UAV_06_F							{cost = 500;	requirements[]={};	};	// "AL-6 Pelican";
				//class B_UAV_06_medical_F					{cost = 500;	requirements[]={};	};	// "AL-6 Pelican medical";
				//class B_AAA_System_01_F 					{cost = 8000;	requirements[]={};	};	// "Phalax";

			};
		};
		class EAST
		{
			class Infantry
			{
				class UK3CB_CW_SOV_O_LATE_VDV_RIF_1							{cost = 20;		requirements[]={};	};	// "Rifleman"
				class UK3CB_CW_SOV_O_LATE_VDV_CREW 							{cost = 15;		requirements[]={};	};	// "Crewman"
				class UK3CB_CW_SOV_O_LATE_HELI_PILOT 					    {cost = 10;		requirements[]={};	};	// "Helicopter Pilot"
				class UK3CB_CW_SOV_O_LATE_JET_PILOT 					    {cost = 10;		requirements[]={};	};	// "Pilot"
				class UK3CB_CW_SOV_O_LATE_VDV_GL						    {cost = 50;		requirements[]={};	};	// "Grenadier"
				class UK3CB_CW_SOV_O_LATE_VDV_MD							{cost = 20;		requirements[]={};	};	// "Combat Life Saver"
				class UK3CB_CW_SOV_O_LATE_VDV_MG						    {cost = 50;		requirements[]={};	};	// "Autorifleman"
				class UK3CB_CW_SOV_O_LATE_VDV_MG_ASST						{cost = 25;		requirements[]={};	};	// "Ammo Bearer"
				class UK3CB_CW_SOV_O_LATE_VDV_MK							{cost = 60;		requirements[]={};	};	// "Marksman"
				class UK3CB_CW_SOV_O_LATE_VDV_ENG					        {cost = 100;	requirements[]={};	};	// "Repair Specialist"
				class UK3CB_CW_SOV_O_LATE_VDV_LAT						    {cost = 100;	requirements[]={};	};	// "Rifleman (AT)"
				class UK3CB_CW_SOV_O_LATE_VDV_AT					        {cost = 150;	requirements[]={};	};	// "Viper Rifleman (AT)"
				class UK3CB_CW_SOV_O_LATE_VDV_AT_ASST						{cost = 150;	requirements[]={};	};	// "Missile Specialist (AT)"
				class UK3CB_CW_SOV_O_LATE_AA						        {cost = 150;	requirements[]={};	};	// "Missile Specialist (AA)"
				class UK3CB_CW_SOV_O_LATE_SF_SNI							{cost = 100;	requirements[]={};	};	// "Sniper"
			};
			class Vehicles
			{
				class UK3CB_CHD_O_TT650						    {cost = 20;		requirements[]={};	};	// "Quad Bike"
				class UK3CB_CW_SOV_O_LATE_UAZ_Closed			{cost = 100;	requirements[]={};	};	// "Qilin (Unarmed)"
				class UK3CB_CW_SOV_O_LATE_BRDM2_UM				{cost = 300;	requirements[]={};	};	// "Ifrit"
				class UK3CB_CW_SOV_O_LATE_Gaz66_Covered			{cost = 200;	requirements[]={};	};	// "Tempest Transport"
				class UK3CB_CW_SOV_O_LATE_Kraz255_Fuel			{cost = 500;	requirements[]={};	};	// "Tempest Fuel"
				class UK3CB_CW_SOV_O_LATE_Gaz66_Med				{cost = 350;	requirements[]={};	};	// "Tempest Medical"
				class UK3CB_CW_SOV_O_LATE_UAZ_MG				{cost = 200;	requirements[]={};	};	// "Offroad (HMG)"
				class UK3CB_CW_SOV_O_LATE_UAZ_AGS30				{cost = 500;	requirements[]={};	};	// "Qilin (AT)"
				class UK3CB_CW_SOV_O_LATE_UAZ_SPG9				{cost = 500;	requirements[]={};	};	// "Offroad (AT)"
				class UK3CB_CW_SOV_O_LATE_Gaz66_Repair			{cost = 2000;	requirements[]={};	};	// "Tempest Repair"
				class UK3CB_CW_SOV_O_LATE_Gaz66_Ammo			{cost = 3000;	requirements[]={};	};	// "Tempest Ammo"
				
				class UK3CB_CW_SOV_O_LATE_BRDM2_ATGM				{cost = 1500;	requirements[]={};	};	// "Qilin (AT)"
				class UK3CB_CW_SOV_O_LATE_BRDM2						{cost = 1000;	requirements[]={};	};	// "Ifrit HMG"
				class UK3CB_CW_SOV_O_LATE_BTR60			            {cost = 1500;	requirements[]={};	};	// "MSE-3 Marid"
				class UK3CB_CW_SOV_O_LATE_BTR80				        {cost = 2000;	requirements[]={};	};	// "BTR-K Kamysh"
				class UK3CB_CW_SOV_O_LATE_BMP1				        {cost = 3700;	requirements[]={};	};	// "BTR-K Kamysh"
				class UK3CB_CW_SOV_O_LATE_BMD1				        {cost = 4000;	requirements[]={};	};	// "BTR-K Kamysh"
				class UK3CB_CW_SOV_O_LATE_VDV_Ural_Zu23				{cost = 1500;	requirements[]={};	};	// "ZSU-39 Tigris"
				class UK3CB_CW_SOV_O_LATE_MTLB_ZU23					{cost = 1500;	requirements[]={};	};	// "ZSU-39 Tigris"
				class UK3CB_CW_SOV_O_LATE_ZsuTank					{cost = 2500;	requirements[]={};	};	// "ZSU-39 Tigris"
				class UK3CB_CW_SOV_O_LATE_2S6M_Tunguska				{cost = 3000;	requirements[]={};	};	// "ZSU-39 Tigris"
				class UK3CB_CW_SOV_O_LATE_T55						{cost = 5000;	requirements[]={};	};	// "T-100 Varsuk"
				class UK3CB_CW_SOV_O_LATE_T72A						{cost = 8000;	requirements[]={};	};	// "T-100 Varsuk"
				class UK3CB_CW_SOV_O_LATE_T80BVK					{cost = 10000;	requirements[]={};	};	// "T-100 Varsuk"
				class UK3CB_CW_SOV_O_LATE_T80U						{cost = 13000;	requirements[]={};	};	// "T-140 Angara"
				class UK3CB_CW_SOV_O_LATE_2S1					    {cost = 18000;	requirements[]={};	};	// "T-140K Angara"
				class UK3CB_CW_SOV_O_LATE_2S3					    {cost = 18000;	requirements[]={};	};	// "T-140K Angara"
				class UK3CB_CW_SOV_O_LATE_BM21						{cost = 20000;	requirements[]={};	};	// "2S9 Sochor"
				

			};
			class Aircraft
			{
				class UK3CB_CW_SOV_O_LATE_Mi8				    {cost = 900;	requirements[]={"H"};	};	// "PO-30 Orca (Unarmed)"
				class UK3CB_CW_SOV_O_LATE_Mi8AMTSh		        {cost = 5000;	requirements[]={"H"};	};	// "PO-30 Orca"
				class UK3CB_CW_SOV_O_LATE_Mi_24P		        {cost = 12000;	requirements[]={"H"};	};	// "Mi-48 Kajman"
				class UK3CB_CW_SOV_O_EARLY_Antonov_AN2_Armed		{cost = 1000;	requirements[]={"A"};	};	// "To-199 Neophron (CAS)"
				class UK3CB_CW_SOV_O_LATE_Su25SM					{cost = 37000;	requirements[]={"A"};	};	// "To-201 Shikra"
				class UK3CB_KDF_O_MIG21_AA					        {cost = 37000;	requirements[]={"A"};	};	// "To-201 Shikra"
				class UK3CB_CW_SOV_O_LATE_TU95MS		            {cost = 50000;	requirements[]={"A"};	};	// "To-201 Shikra Stealth"
				
			};
			class Naval
			{
				class UK3CB_CHD_W_O_Small_Boat_Wood					{cost = 100;	requirements[]={"W"};	};	// "Assault Boat"
				class UK3CB_CHD_O_Small_Boat_Closed					{cost = 100;	requirements[]={"W"};	};	// "Assault Boat"
				class rhs_bmk_t					                    {cost = 100;	requirements[]={"W"};	};	// "Assault Boat"
				class UK3CB_MDF_O_RHIB					            {cost = 100;	requirements[]={"W"};	};	// "Assault Boat"
				class UK3CB_CHD_O_Fishing_Boat_VIV_FFV				{cost = 100;	requirements[]={"W"};	};	// "Assault Boat"
				class UK3CB_CHD_O_Fishing_Boat_DSHKM				{cost = 100;	requirements[]={"W"};	};	// "Assault Boat"
				class UK3CB_CHD_O_Fishing_Boat_SPG9					{cost = 100;	requirements[]={"W"};	};	// "Assault Boat"
				class UK3CB_CHD_O_Fishing_Boat_Zu23					{cost = 100;	requirements[]={"W"};	};	// "Assault Boat"
				class UK3CB_CHD_O_Fishing_Boat_Zu23_front			{cost = 100;	requirements[]={"W"};	};	// "Speedboat HMG"
				class UK3CB_CHC_O_Fishing_Vessel					{cost = 100;	requirements[]={"W"};	};	// "SDV"
			};
			class Gear
			{
				class Box_East_Ammo_F						{cost = 50;		requirements[]={};	};	// "Basic Ammo [CSAT]"
				class Box_East_Grenades_F					{cost = 50;		requirements[]={};	};	// "Grenades [CSAT]"
				class Box_East_Wps_F						{cost = 100;	requirements[]={};	};	// "Basic Weapons [CSAT]"
				class Box_East_AmmoOrd_F					{cost = 300;	requirements[]={};	};	// "Explosives [CSAT]"
				class Box_East_WpsLaunch_F					{cost = 500;	requirements[]={};	};	// "Launchers [CSAT]"
				class Box_East_WpsSpecial_F					{cost = 600;	requirements[]={};	};	// "Special Weapons [CSAT]"
				class O_supplyCrate_F						{cost = 700;	requirements[]={};	};	// "Supply Box [CSAT]"
				class Box_East_AmmoVeh_F					{cost = 800;	requirements[]={};	};	// "Vehicle Ammo [CSAT]"
			};
			class Defences
			{
				class UK3CB_CW_SOV_O_Late_PKM_Low							{cost = 300;	requirements[]={};	};	// "Mk30 HMG .50"
				class UK3CB_CW_SOV_O_Late_PKM_High						{cost = 400;	requirements[]={};	};	// "Mk30 HMG .50 (Raised)"
				class UK3CB_CW_SOV_O_Late_NSV							{cost = 550;	requirements[]={};	};	// "Mk32 GMG 20 mm"
				class UK3CB_CW_SOV_O_Late_DSHkM_Mini_TriPod						{cost = 650;	requirements[]={};	};	// "Mk32 GMG 20 mm (Raised)"
				class UK3CB_CW_SOV_O_Late_DSHKM						{cost = 650;	requirements[]={};	};	// "Mk32 GMG 20 mm (Raised)"
				class UK3CB_CW_SOV_O_Late_Igla_AA_pod							{cost = 300;	requirements[]={};	};	// "Static Titan Launcher (AA) [CSAT]"
				class UK3CB_CW_SOV_O_Late_Metis							{cost = 300;	requirements[]={};	};	// "Static Titan Launcher (AT) [CSAT]"
				class O_Radar_System_02_F					{cost = 1000;	requirements[]={};	offset[]={0, 5.3, 0};};	// "R-750 Cronus Radar"
				class UK3CB_CW_SOV_O_Late_ZU23					{cost = 1000;	requirements[]={};	offset[]={0, 5.3, 0};};	// "R-750 Cronus Radar"
				class UK3CB_CW_SOV_O_Late_2b14_82mm							{cost = 6500;	requirements[]={};	};	// "Mortar"
				class UK3CB_CW_SOV_O_Late_D30							{cost = 7000;	requirements[]={};	};	// "Mortar"

				class UK3CB_CW_SOV_O_Late_PKM_nest						{cost = 800;	requirements[]={};	};	// "UGAV rcws"
				class UK3CB_CW_SOV_O_Late_SPG9					{cost = 500;	requirements[]={};	};	// "UGAV demining"
				class UK3CB_CW_SOV_O_Late_Searchlight					{cost = 250;	requirements[]={};	offset[]={0, 2, 0};};	// "Semi Circle Sand bags"
				class Land_BagFence_Round_F					{cost = 250;	requirements[]={};	offset[]={0, 2, 0};};	// "Semi Circle Sand bags"
				class Land_Razorwire_F						{cost = 250;	requirements[]={};	offset[]={0, 5, 0};};	// "Razor Wire Fence"
				class Land_DragonsTeeth_01_1x1_new_F		{cost = 500;	requirements[]={};	offset[]={0, 2, 0};};	// "Tank barrier"
				//class O_UAV_02_F							{cost = 25000;	requirements[]={"A"};	};	// "K40 AT"
				//class O_UAV_02_CAS_F						{cost = 25000;	requirements[]={"A"};	};	// "K40 LGB"
				//class O_T_UAV_04_CAS_F					{cost = 25000;	requirements[]={"A"};	};	// "KH-3A CAS"
				//class O_UAV_01_F							{cost = 500;	requirements[]={};	};	// "AR-2 Darter"
				//class O_UAV_06_F							{cost = 500;	requirements[]={};	};	// "AL_6 Pelican"
				//class O_UAV_06_medical_F					{cost = 500;	requirements[]={};	};	// "AL_6 Pelican Medical"
				//class B_AAA_System_01_F 					{cost = 8000;	requirements[]={};	};	// "Phalax";

			};
		};
	};
};